# Copyright (C) 2026 - present Jeton Rama, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

sonar.projectKey=hono-appserver
sonar.projectVersion=2026.4.1
sonar.scm.disabled=true
sonar.sources=src
sonar.tests=test/integration
sonar.typescript.tsconfigPaths=./tsconfig.json
sonar.javascript.environments=node
sonar.host.url=http://localhost:9000
# SonarQube Token von http://localhost:9000: MyAccount > Security
sonar.token=squ_94ca9f1f375e14c46425b9cc1a66b964764d7faa
sonar.exclusions=\
node_modules/**,\
.scannerwork/*,\
.vscode/*,\
coverage/**,\
dist/**,\
extras/**,\
log/*,\
prisma/*,\
src/generated/**,\
test/lasttest/*
